<?PHP
//
// Dropbox 2.1
// Copyright (C) 2006 Jeffrey Frey, frey at udel dot edu
//
// Based on the original PERL dropbox written by Doke Scott.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

//
// This file was generated by the config.php script
//

define('NSSDROPBOX_BASE_DIR','/var/www/dropbox/');
define('NSSDROPBOX_LIB_DIR','/var/www/dropbox/lib/');
define('NSSDROPBOX_DATA_DIR','/export/images/dropbox_data/');

//
// Buttons can be skinned by adding a new directory in image/ and
// using its name as the value for NSSTHEME here.  We
// include several button themes in the package:
//
define('NSSTHEME','default');
//define('NSSTHEME','flat');
//define('NSSTHEME','flat2');
//define('NSSTHEME','blue');
//define('NSSTHEME','algae');
//define('NSSTHEME','ud');
//define('NSSTHEME','duracell');

//
// Preferences are stored as a hashed array.  Inline comments
// indicate what everything is for.
//
$NSSDROPBOX_PREFS = array(
  'dropboxName'          => 'University of Reading ASSET Dropbox Service',
  'dropboxDomain'        => 'reading.ac.uk',
  'dropboxDomains'       => array('reading.ac.uk', 'student.reading.ac.uk', 'henley.reading.ac.uk', 'henley.com'),
  'dropboxDirectory'     => NSSDROPBOX_DATA_DIR."dropoffs",
  'dropboxDatabase'      => NSSDROPBOX_DATA_DIR."dropbox.sqlite",
  'logFilePath'          => NSSDROPBOX_DATA_DIR."dropbox.log",
  'numberOfDaysToRetain' => 14,
  'showRecipsOnPickup'   => FALSE,
  'maxBytesForDropoff'   => 2097152000,
  'maxBytesForFile'      => 2097152000,
  'authenticator' => 'AD',
  'authIMAPServer' => '{imap.reading.ac.uk:143/imap/tls/novalidate-cert}INBOX',
  'authADDomain' => 'rdg-home.ad.rdg.ac.uk',
  'authADServer' => 'ldap://vidc1.rdg.ac.uk/',
  'authUserFormalDesc' => 'University of Reading',
  'authUserShortDesc' => 'AuthUser',
  'emailSenderAddr' => 'UoR ASSET Dropbox Service <its-automated-email@reading.ac.uk>',
  'authAdmins' => array( "viswakln", "suqsandc", "vj901307", "vis08w", "sis05kol" ),
  'contactInfo' => 'Dropbox Service (c) 2009',
  'cookieName' => 'dropbox-session',
  'cookieSecret' => '2da5599245939ab4f1335e1df80af0bb',
  'cookieTTL' => '900',
  'referralSecret' => 'UoRDropbox4ASSET'
);

//
// This global array contains terms that will be replaced automatically
// throughout the interface:
//
$DROPBOX_DICTIONARY = array(
  'Authentication'        => 'Authentication',
  'Username'              => 'Username',
  'username'              => 'username',
  'username-regex'        => '/^([a-z0-9][a-z0-9\_\.]*)$/'
);
?>
